import { createContext, useContext, useState, useCallback, useEffect } from 'react'
import { useLocalStorage } from '../hooks/useLocalStorage'

const NotificationContext = createContext(null)

/**
 * NotificationContext
 *
 * Stores real notifications generated by the app (appointment updates,
 * payment confirmations, new registrations etc).
 *
 * Notifications are persisted to localStorage so they survive page refreshes.
 * The addNotif() function is called by service mutators after successful API calls.
 *
 * type: 'appointment' | 'billing' | 'patient' | 'system'
 */
export const NotificationProvider = ({ children }) => {
  const [notifs, setNotifs] = useLocalStorage('clinic_notifs', [])

  const unreadCount = notifs.filter(n => !n.read).length

  const addNotif = useCallback((notif) => {
    const entry = {
      id:    Date.now() + Math.random(),
      type:  notif.type  || 'system',
      title: notif.title || 'Notification',
      body:  notif.body  || '',
      time:  'just now',
      read:  false,
      ts:    Date.now(),
    }
    setNotifs(prev => [entry, ...prev].slice(0, 50)) // keep last 50
  }, [setNotifs])

  const markRead = useCallback((id) => {
    setNotifs(prev => prev.map(n => n.id === id ? { ...n, read: true } : n))
  }, [setNotifs])

  const markAllRead = useCallback(() => {
    setNotifs(prev => prev.map(n => ({ ...n, read: true })))
  }, [setNotifs])

  const dismiss = useCallback((id) => {
    setNotifs(prev => prev.filter(n => n.id !== id))
  }, [setNotifs])

  const clearAll = useCallback(() => setNotifs([]), [setNotifs])

  // Humanise timestamps every minute
  useEffect(() => {
    const timer = setInterval(() => {
      setNotifs(prev => prev.map(n => {
        const mins = Math.floor((Date.now() - (n.ts || Date.now())) / 60000)
        const time = mins < 1  ? 'just now'
                   : mins < 60 ? `${mins}m ago`
                   : mins < 1440 ? `${Math.floor(mins/60)}h ago`
                   : `${Math.floor(mins/1440)}d ago`
        return { ...n, time }
      }))
    }, 60000)
    return () => clearInterval(timer)
  }, [setNotifs])

  return (
    <NotificationContext.Provider value={{
      notifs, unreadCount,
      addNotif, markRead, markAllRead, dismiss, clearAll,
    }}>
      {children}
    </NotificationContext.Provider>
  )
}

export const useNotifications = () => {
  const ctx = useContext(NotificationContext)
  if (!ctx) throw new Error('useNotifications must be inside NotificationProvider')
  return ctx
}
